// This file is automatically generated. Do not modify it manually.

package main

var manifest = struct {
	ID      string
	Version string
}{
	ID:      "com.mattermost.plugin-todo",
	Version: "0.3.0",
}
