#!/bin/sh
cd ../../../
git clone --depth 1 https://github.com/mattermost/mattermost.git
cd mattermost

source ~/.nvm/nvm.sh
nvm install

cd webapp
npm i

cd ../e2e-tests/playwright

npm i
npx playwright install --with-deps

cd ../../../mattermost-plugin-todo/e2e/playwright
npm i